CC = clang
CFLAGS = -Wall
LDFLAGS = -lglut -lGL -lGLU

t1: exp1t1.c
	$(CC) $< -o $@ $(LDFLAGS)
t2: exp1t2.c
	$(CC) $< -o $@ $(LDFLAGS)
t3: exp1t3.c
	$(CC) $< -o $@ $(LDFLAGS)
t4: exp1t4.c	
	$(CC) $< -o $@ $(LDFLAGS)
t5: exp1t5.c
	$(CC) $< -o $@ $(LDFLAGS)
t6: exp1t6.c
	$(CC) $< -o $@ $(LDFLAGS)
t7: exp1t7.c
	$(CC) $< -o $@ $(LDFLAGS)
t8: exp1t8.c
	$(CC) $< -o $@ $(LDFLAGS)

clean: 
	rm -f t1 t2 t3 t4 t5 t6 t7 t8