CC = clang
CFLAGS = -Wall
LDFLAGS = -lglut -lGL -lGLU -lm -lSOIL

t1: exp2t1.c
	$(CC) $< -o $@ $(LDFLAGS)
t2: exp2t2.c
	$(CC) $< -o $@ $(LDFLAGS)
t3: exp2t3.c
	$(CC) $< -o $@ $(LDFLAGS)
t4: exp2t4.c
	$(CC) $< -o $@ $(LDFLAGS)
t5: exp2t5.c
	$(CC) $< -o $@ $(LDFLAGS)
t6: exp2t6.c
	$(CC) $< -o $@ $(LDFLAGS)
t7: exp2t7.c
	$(CC) $< -o $@ $(LDFLAGS)
t8: exp2t8.c
	$(CC) $< -o $@ $(LDFLAGS)

clean: 
	rm -f t1 t2 t3 t4 t5 t6 t7 t8